### ISSUE TITLE
Is there any special consideration of initialization ?

### ISSUE THREAD

**Issue by CoinCheung** [megvii-model/FunnelAct#10]
Hi,

Since we use kaiming_normal to initialize conv layers followed by relu, and xavier to initiailize linear conv layers. Is there any specification to normalize the conv layers when using FReLU. Besides, there is a conv layer within the FReLU module, how could I initialize this embedded conv layer?

**Comment by nmaac** [comment]
@CoinCheung For the dw-conv in the FReLU, we suggest to initialize with mean=0, std=0.01; for other conv layers and linear layers we suggest the normal initializations.

**Comment by CoinCheung** [comment]
Thanks, I will have a try of this.
