### ISSUE TITLE
Why do you  apply relu instead of frelu to first activation function?

### ISSUE THREAD

**Issue by phalanx-hk** [megvii-model/FunnelAct#3]
Thanks for your great work! 
I have one question. you apply relu activation to first activation function like this.
https://github.com/megvii-model/FunnelAct/blob/f2b6c9ddae15c40fb8a3a3443854a239189720e6/resnet/resnet.py#L281-L286
Is it better than applying frelu? And is there a reason for that?
Thank you!

**Comment by nmaac** [comment]
@phalanx-hk  We note that the modern CNN structures are finely designed with the ReLU activation, therefore applying FReLU to the ReLU networks is flexible: you can replace all ReLU with FReLU, you can also replace some of them. Finding an optimum replacement can further improve the performance but beyond the focus of this work. To deal with this issue, we focused on the activations in each bottleneck and we found a comparable result whether we change the first ReLU.

**Comment by phalanx-hk** [comment]
@nmaac Ok, I understand. Thanks for your feedback!
