### ISSUE TITLE
replace frelu with depth-wise conv + relu

### ISSUE THREAD

**Issue by a157801** [megvii-model/FunnelAct#6]
Maybe replacing frelu with depth-wise conv + relu should be a necessary ablation study experiment.

**Comment by nmaac** [comment]
We have already compared them in the original paper (Table 5, Model E).

**Comment by a157801** [comment]
Thanks a lot. But I am a little confused that the model is both trained and evaluated with dw conv + relu or trained with frelu and evalued with dw + relu.

**Comment by nmaac** [comment]
Model E in Table 5 uses the former.
