### ISSUE TITLE
What's the difference between funnelact and maxout?

### ISSUE THREAD

**Issue by jia1995** [megvii-model/FunnelAct#8]

**Comment by nmaac** [comment]
Hi @jia1995 , actually this question is similar to:
* "What's the difference between maxout and relu?"
* "What's the difference between maxout and prelu?"

To answer it,
* all of them use the max operator;
* concept methods are different from concrete methods. Maxout presents a good and very **general concept**, it can approximate relu/prelu/frelu, however, as a concept method, maxout **cannot replace** these specific and practical methods;
* funnelact is designed specifically for visual tasks which is not the focus of maxout;
* maxout usually increases model size a lot, while funnelact does not.

**Comment by jia1995** [comment]
@nmaac 
Thank you for your quick reply!
I understand.
