### ISSUE TITLE
base_width报错

### ISSUE THREAD

**Issue by ZangHuanyu** [megvii-model/FunnelAct#9]
@nmaac @megvii-model 作者求问，这个报错是怎么回事，定义class的时候除了添加我自己设计的网络参数，base_width这个参数都是照着repo给的位置加上去的，对照了一遍并没有哪个地方多加。在此先感谢！

File "D:\Github_code\Wujie\models\pyconv.py", line 389, in pyconvresnet50
    model = PyConvResNet(PyConvBottleneck, [3, 4, 6, 3], **kwargs)
  File "D:\Github_code\Wujie\models\pyconv.py", line 265, in __init__
    self.layer1 = self._make_layer(block, 64, layers[0], stride=2, norm=norm, pyconv_kernels=[3, 5, 7, 9], pyconv_groups=[1, 4, 8, 16])
  File "D:\Github_code\Wujie\models\pyconv.py", line 318, in _make_layer
    layers.append(block(self.inplanes, planes, stride, norm, dilation=previous_dilation, norm=norm,pyconv_kernels=pyconv_kernels, pyconv_groups=pyconv_groups, base_width=self.base_width))
TypeError: __init__() got multiple values for argument 'base_width'

**Comment by nmaac** [comment]
似乎不是本repo相关问题，请核查一下是否误贴到我们的repo @ZangHuanyu ，谢谢。
